// <auto-generated />
// This file is generated. Do not modify manually.
#nullable enable

namespace CreativeArcana.Audio
{
    public enum AudioLibraryId
    {
        Brave,
        Build,
        Click,
        Error,
        Music1,
        Music2,
        Music_Ambient,
        ShotGun_1,
        ShotGun_2,
        ShotGun_3,
        ShotGuns_Shuffle,
        UI_Sequential,
        Voice_Random
    }
}
