// <auto-generated />
// This file is generated. Do not modify manually.
#nullable enable
using System;

namespace CreativeArcana.Audio
{
    public static class AudioLibraryIdExtensions
    {
        public static AudioId ToAudioId(this AudioLibraryId value)
        {
            return value switch
            {
                AudioLibraryId.Brave => new AudioId("Brave"),
                AudioLibraryId.Build => new AudioId("Build"),
                AudioLibraryId.Click => new AudioId("Click"),
                AudioLibraryId.Error => new AudioId("Error"),
                AudioLibraryId.Music1 => new AudioId("Music1"),
                AudioLibraryId.Music2 => new AudioId("Music2"),
                AudioLibraryId.Music_Ambient => new AudioId("Music_Ambient"),
                AudioLibraryId.ShotGun_1 => new AudioId("ShotGun_1"),
                AudioLibraryId.ShotGun_2 => new AudioId("ShotGun_2"),
                AudioLibraryId.ShotGun_3 => new AudioId("ShotGun_3"),
                AudioLibraryId.ShotGuns_Shuffle => new AudioId("ShotGuns_Shuffle"),
                AudioLibraryId.UI_Sequential => new AudioId("UI_Sequential"),
                AudioLibraryId.Voice_Random => new AudioId("Voice_Random"),
                _ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
            };
        }

        public static AudioHandle Play(this IAudioService audioService, AudioLibraryId value, float fadeInDuration = 0, DuckingProfile duckingProfile = default)
        {
            if (audioService == null)
                throw new ArgumentNullException(nameof(audioService));

            return audioService.Play(value.ToAudioId(), fadeInDuration, duckingProfile);
        }

        public static AudioHandle CrossFadePlay(this IAudioService audioService, AudioHandle from, AudioLibraryId to, float fadeInDuration = 1, float fadeOutDuration = 1, DuckingProfile duckingProfile = default)
        {
            if (audioService == null)
                throw new ArgumentNullException(nameof(audioService));

            return audioService.CrossFadePlay(from, to.ToAudioId(), fadeInDuration, fadeOutDuration, duckingProfile);
        }
    }
}
