using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace CreativeArcana.Audio.Editor
{
    public static class AudioIdCodeGenerator
    {
        private const string DefaultNamespace = "CreativeArcana.Audio";
        private static readonly HashSet<string> PendingPaths = new();

        private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
            "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw",
            "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
            "virtual", "void", "volatile", "while"
        };

        public static void RequestGenerate(AudioLibrary library, string outputFolderPath)
        {
            if (library == null || string.IsNullOrWhiteSpace(outputFolderPath))
                return;

            outputFolderPath = NormalizePath(outputFolderPath);

            if (!PendingPaths.Add(outputFolderPath))
                return;

            EditorApplication.delayCall += () =>
            {
                try
                {
                    Generate(library, outputFolderPath);
                }
                catch (Exception ex)
                {
                    Debug.LogException(ex);
                }
                finally
                {
                    PendingPaths.Remove(outputFolderPath);
                }
            };
        }

        private static bool Generate(AudioLibrary library, string outputFolderPath)
        {
            if (library == null || string.IsNullOrWhiteSpace(outputFolderPath))
                return false;

            outputFolderPath = NormalizePath(outputFolderPath);

            var entries = GetValidEntries(library);
            var enumName = GetGeneratedEnumName(library.name);
            var mapperName = GetGeneratedMapperName(enumName);

            var enumCode = BuildEnumCode(enumName, entries);
            var mapperCode = BuildMapperCode(enumName, mapperName, entries);

            var enumPath = GetGeneratedTypePath(outputFolderPath, enumName);
            var mapperPath = GetGeneratedTypePath(outputFolderPath, mapperName);

            var enumChanged = WriteIfChanged(enumPath, enumCode);
            var mapperChanged = WriteIfChanged(mapperPath, mapperCode);

            if (enumChanged || mapperChanged)
                AssetDatabase.Refresh();

            return enumChanged || mapperChanged;
        }

        private static EntryData[] GetValidEntries(AudioLibrary library)
        {
            if (library.Entries == null)
                return Array.Empty<EntryData>();

            var usedNames = new HashSet<string>(StringComparer.Ordinal);

            return library.Entries
                .Where(e => e != null && !string.IsNullOrWhiteSpace(e.Id.Value))
                .OrderBy(e => e.Id.Value, StringComparer.Ordinal)
                .Select(e =>
                {
                    var rawId = e.Id.Value;
                    var enumMember = MakeUniqueIdentifier(SanitizeIdentifier(rawId), usedNames);

                    return new EntryData(rawId, enumMember);
                })
                .ToArray();
        }

        private static string BuildEnumCode(string enumName, EntryData[] entries)
        {
            var sb = new StringBuilder(2048);

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// This file is generated. Do not modify manually.");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {DefaultNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public enum {enumName}");
            sb.AppendLine("    {");

            if (entries.Length > 0)
            {
                for (var i = 0; i < entries.Length; i++)
                {
                    var suffix = i < entries.Length - 1 ? "," : string.Empty;
                    sb.AppendLine($"        {entries[i].EnumMemberName}{suffix}");
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string BuildMapperCode(string enumName, string mapperName, EntryData[] entries)
        {
            var sb = new StringBuilder(4096);

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// This file is generated. Do not modify manually.");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine($"namespace {DefaultNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {mapperName}");
            sb.AppendLine("    {");

            sb.AppendLine($"        public static AudioId ToAudioId(this {enumName} value)");
            sb.AppendLine("        {");
            sb.AppendLine("            return value switch");
            sb.AppendLine("            {");

            foreach (var entry in entries)
            {
                var escapedId = EscapeStringLiteral(entry.RawId);
                sb.AppendLine($"                {enumName}.{entry.EnumMemberName} => new AudioId(\"{escapedId}\"),");
            }

            sb.AppendLine("                _ => throw new ArgumentOutOfRangeException(nameof(value), value, null)");
            sb.AppendLine("            };");
            sb.AppendLine("        }");

            sb.AppendLine();

            sb.AppendLine($"        public static AudioHandle Play(this IAudioService audioService, {enumName} value, float fadeInDuration = 0, DuckingProfile duckingProfile = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (audioService == null)");
            sb.AppendLine("                throw new ArgumentNullException(nameof(audioService));");
            sb.AppendLine();
            sb.AppendLine("            return audioService.Play(value.ToAudioId(), fadeInDuration, duckingProfile);");
            sb.AppendLine("        }");
            
            sb.AppendLine();
            sb.AppendLine($"        public static AudioHandle CrossFadePlay(this IAudioService audioService, AudioHandle from, {enumName} to, float fadeInDuration = 1, float fadeOutDuration = 1, DuckingProfile duckingProfile = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (audioService == null)");
            sb.AppendLine("                throw new ArgumentNullException(nameof(audioService));");
            sb.AppendLine();
            sb.AppendLine("            return audioService.CrossFadePlay(from, to.ToAudioId(), fadeInDuration, fadeOutDuration, duckingProfile);");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }


        private static string GetGeneratedEnumName(string libraryName)
        {
            var sanitized = SanitizeIdentifier(string.IsNullOrWhiteSpace(libraryName) ? "AudioLibrary" : libraryName);
            return $"{sanitized}Id";
        }

        private static string GetGeneratedMapperName(string enumName)
        {
            return $"{enumName}Extensions";
        }

        private static string GetGeneratedTypePath(string outputFolderPath, string typeName)
        {
            return NormalizePath(Path.Combine(outputFolderPath, $"{typeName}.g.cs"));
        }

        private static string SanitizeIdentifier(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
                return "Audio";

            var sb = new StringBuilder(value.Length);
            var capitalizeNext = true;

            foreach (var c in value)
            {
                if (char.IsLetterOrDigit(c))
                {
                    if (sb.Length == 0 && char.IsDigit(c))
                        sb.Append('_');

                    sb.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                    capitalizeNext = false;
                }
                else
                {
                    if (sb.Length > 0 && sb[^1] != '_')
                        sb.Append('_');

                    capitalizeNext = true;
                }
            }

            var result = sb.ToString().Trim('_');

            if (string.IsNullOrEmpty(result))
                result = "Audio";

            if (char.IsDigit(result[0]))
                result = "_" + result;

            if (CSharpKeywords.Contains(result))
                result = "@" + result;

            return result;
        }

        private static string MakeUniqueIdentifier(string baseName, HashSet<string> usedNames)
        {
            var finalName = baseName;
            var index = 1;

            while (!usedNames.Add(finalName))
            {
                finalName = $"{baseName}_{index++}";
            }

            return finalName;
        }

        private static string EscapeStringLiteral(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static bool WriteIfChanged(string path, string content)
        {
            if (File.Exists(path))
            {
                var existing = File.ReadAllText(path);
                if (string.Equals(existing, content, StringComparison.Ordinal))
                    return false;
            }

            var directory = Path.GetDirectoryName(path);
            if (!string.IsNullOrWhiteSpace(directory))
                Directory.CreateDirectory(directory);

            File.WriteAllText(path, content, Encoding.UTF8);
            return true;
        }

        private static string NormalizePath(string path)
        {
            return path.Replace("\\", "/");
        }

        private readonly struct EntryData
        {
            public EntryData(string rawId, string enumMemberName)
            {
                RawId = rawId;
                EnumMemberName = enumMemberName;
            }

            public string RawId { get; }
            public string EnumMemberName { get; }
        }
    }
}
